//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorrenjusridhar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_blog
    {
        public int id { get; set; }
        public string post_title { get; set; }
        public string short_description { get; set; }
        public string long_description { get; set; }
        public string post_image { get; set; }
        public string post_youtube { get; set; }
        public Nullable<int> post_like { get; set; }
        public Nullable<int> post_comment { get; set; }
        public Nullable<int> post_view { get; set; }
        public string created_on { get; set; }
        public string updated_on { get; set; }
    }
}
