//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorrenjusridhar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_books
    {
        public int id { get; set; }
        public string book_title { get; set; }
        public string book_link { get; set; }
        public string book_description { get; set; }
        public string book_image { get; set; }
    }
}
